### ISSUE TITLE
建议使用语义化版本号重新打一个标签

### ISSUE THREAD

**Issue by voidint** [vimsucks/wxwork-bot-go#8]
当前使用了`v1.0`这样的标签名，因为它不满足语义化版本号的范式，导致go mod引入该依赖库后，go.mod中内容变成了这样：
```
github.com/vimsucks/wxwork-bot-go v0.0.0-20221213061339-fcbcd88ede1c
```

**Comment by voidint** [comment]
建议使用`v1.0.0`的标签

**Comment by vimsucks** [comment]
done, see https://github.com/vimsucks/wxwork-bot-go/releases/tag/v1.0.0
